#!/bin/bash

# Clear out results file
echo Version,GC,Method,Size,Duration >times.csv

# Set PYENV_VERSION to each value from `pyenv versions`.
# Rely on BSD sed, for the loss.
versions=$(pyenv versions | \
           sed -nE 's_^[[:space:]]*\*?[[:space:]]*([^[:space:]]+).*_\1_p')

for ver in $versions; do
    if [ "$ver" != "system" ]; then
        export PYENV_VERSION=$ver
        ./trial
    fi
done
